### PR TITLE
Fix/key ceremony serialization

### LINKED ISSUE #206: 🐞 Key ceremony backups not verifiable
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Key ceremony was not backing up properly. Add unit tests and resolve.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AddressXception**
[//]: # (🚨 Please review the CONTRIBUTING.md in this repository. 💔Thank you!)

### Issue
*Link your PR to an issue*

Fixes the key ceremony serialization/hydration issues

Fixes #206

### Description
*Please describe your pull request.*

very specifically the relationship between the Guardian and the Gaurdian Private Record was a painpoint. the rehyudration forom the disk and use of the ojbect and then passing it's internal state around was giving me issues when i put it into a unit test (high speed quasi-concurrent).

the othe thing was the relationships between ElGamalKeyPair, ElectionKeyPair and EncryptionKeyPair. I simplified that stuff a bit and added Newtonsoft.Json with custom serializers for our native types that seems to be working much better.

those were the two big areas. most of the rest of it is just making sure that the disposable implementations were accounting for the fact that objects can actyually be null even if they are not nullable and making sure there are copy constructors for objects

### Testing
*Describe the best way to test or validate your PR.*

### CODE REVIEW

File: bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/ElGamalCiphertext.cs [hunk 1]
```diff
@@ -73,6 +73,18 @@ public ElGamalCiphertext(ElementModP pad, ElementModP data)
             Handle = handle;
         }
 
+        public ElGamalCiphertext(ElGamalCiphertext other)
+        {
+            using (var pad = new ElementModP(other.Pad))
+            using (var data = new ElementModP(other.Data))
```
Comment (SteveMaier-IRT) [inline bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/ElGamalCiphertext.cs:79]: Creating these new ElementModP were not really needed since the ElGamalCiphertext::make creates new ones with make_unique and in that constructor it already does a clone

File: bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/Guardian/Guardian.cs [hunk 2]
```diff
@@ -225,38 +256,44 @@ public List<ElectionPartialKeyBackup> ShareElectionPartialKeyBackups()
...
+            throw new ArgumentNullException(nameof(recipientPublicKey));
+        }
+
+        var coordinate = myPolynomial.ComputeCoordinate(
+            recipientPublicKey.SequenceOrder);
         var seed = GetBackupSeed(
-                receiverGuardianPublicKey.OwnerId,
-                receiverGuardianPublicKey.SequenceOrder);
+                recipientPublicKey.OwnerId,
+                recipientPublicKey.SequenceOrder);
```
Comment (john-s-morgan) [inline bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/Guardian/Guardian.cs:281]: better name 😄

File: bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/Guardian/Guardian.cs [hunk 3]
```diff
@@ -70,6 +70,26 @@ public partial class Guardian : DisposableBase
...
+        ulong sequenceOrder,
+        int numberOfGuardians,
+        int quorum,
+        string keyCeremonyId,
+        Random random)
+    {
+        GuardianId = guardianId;
+        SequenceOrder = sequenceOrder;
+
+        var keyPair = new ElGamalKeyPair(random.NextElementModQ());
```
Comment (john-s-morgan) [inline bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/Guardian/Guardian.cs:84]: We should dispose `random.NextElementModQ()` here

File: bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/Guardian/GuardianStorageExtensions.cs [hunk 4]
```diff
@@ -1,6 +1,7 @@
+﻿using ElectionGuard.Encryption.Utils.Converters;
 using ElectionGuard.UI.Lib.Models;
 using ElectionGuard.UI.Lib.Services;
-using System.Text.Json;
+using Newtonsoft.Json;
```
Comment (john-s-morgan) [inline bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/Guardian/GuardianStorageExtensions.cs:4]: Future TODO: System.Text has vastly improved their JSON support. Look into removing `Newtonsoft`.

File: bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/KeyCeremonyMediator.cs [hunk 5]
```diff
@@ -1,28 +1,86 @@
...
+        _backupService = backupService;
+        _publicKeyService = publicKeyService;
+        _verificationService = verificationService;
         CreateAdminSteps();
         CreateGuardianSteps();
     }
 
-    private List<KeyCeremonyStep> _adminSteps = new();
-    private List<KeyCeremonyStep> _guardianSteps = new();
+    protected readonly IKeyCeremonyService _service;
```
Comment (john-s-morgan) [inline bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/KeyCeremonyMediator.cs:74]: Can this be renamed to `_keyCeremonySerivce`?

File: bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/KeyCeremonyMediator.cs [hunk 6]
```diff
@@ -466,203 +556,178 @@ private async Task<bool> AlwaysRun()
...
         var publicKey = guardian.SharePublicKey();
-
-        // append to key ceremony (db)
-        try
-        {
-            await service.UpdatePublicKeyAsync(keyCeremonyId, currentGuardianUserName, publicKey);
-        }
-        catch (ElectionGuardException)
+        // read isInBounds to ensure the handle is valid
+        if (publicKey == null || publicKey.Key == null || !publicKey.Key.IsInBounds())
```
Comment (john-s-morgan) [inline bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/KeyCeremonyMediator.cs:673]: if the `Key` is not null, can we assume this is in bounds? Or add a check inside the public key

File: bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/KeyCeremonyMediator.cs [hunk 7]
```diff
@@ -739,7 +795,7 @@ private async Task RunStep5()
         {
             guardian!.SaveElectionPartialKeyBackup(backup.Backup!);
             var verification = guardian.VerifyElectionPartialKeyBackup(backup.GuardianId!, keyCeremonyId);
-            if (verification == null)
+            if (verification == null || !verification.Verified)
```
Comment (john-s-morgan) [inline bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/KeyCeremonyMediator.cs:798]: This change is good, but will require UI changes to catch. Right now it interprets the value. If not reverted, this will create a regression.

Comment (john-s-morgan) [reply bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/KeyCeremonyMediator.cs:798]: Future: UI needs to handle a throw on failed verification, and we need to throw on failed verification.

File: bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/KeyCeremonyMediator.cs [hunk 8]
```diff
@@ -750,37 +806,33 @@ private async Task RunStep5()
...
+            _ = await _verificationService.SaveAsync(verification);
         }
 
         // notify change to admin (signalR)
-
     }
 
     private async Task RunStep6()
     {
+        Console.WriteLine("RunStep6");
```
Comment (john-s-morgan) [inline bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/KeyCeremonyMediator.cs:819]: Console.Writeline should be removed.

File: bindings/netstandard/ElectionGuard/ElectionGuard.Encryption.Utils/Converters/ElGamalKeypairConverter.cs [hunk 9]
```diff
@@ -0,0 +1,34 @@
+
+
```
Comment (john-s-morgan) [inline bindings/netstandard/ElectionGuard/ElectionGuard.Encryption.Utils/Converters/ElGamalKeypairConverter.cs:2]: remove pls, ser

File: bindings/netstandard/ElectionGuard/ElectionGuard.Encryption.Utils/Converters/ElGamalKeypairConverter.cs [hunk 10]
```diff
@@ -0,0 +1,34 @@
...
+using System;
+using Newtonsoft.Json;
+using Newtonsoft.Json.Linq;
```
Comment (john-s-morgan) [inline bindings/netstandard/ElectionGuard/ElectionGuard.Encryption.Utils/Converters/ElGamalKeypairConverter.cs:5]: Newtonsoft is not in the project

File: bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/Guardian/GuardianStorageExtensions.cs (hunk 4 above)
Comment (john-s-morgan) [reply bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/Guardian/GuardianStorageExtensions.cs:4]: Newtonsoft is not in project.

File: bindings/netstandard/ElectionGuard/ElectionGuard.Encryption.Utils/ElectionGuard.Encryption.Utils.csproj [hunk 11]
```diff
@@ -141,7 +141,4 @@
     <None Name="Linux" Visible="false" Include="$(ElectionGuardLibs)\Linux\$(PlatformTarget)\$(Configuration)\src\*.so" CopyToOutputDirectory="Always" />
     <None Name="Linux HACL" Visible="false" Include="$(ElectionGuardLibs)\Linux\$(PlatformTarget)\$(Configuration)\libs\hacl\*.so" CopyToOutputDirectory="Always" />
   </ItemGroup>
-  <ItemGroup>
-    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
-  </ItemGroup>
```
Comment (john-s-morgan) [inline bindings/netstandard/ElectionGuard/ElectionGuard.Encryption.Utils/ElectionGuard.Encryption.Utils.csproj:146]: This looks important.

**Review by john-s-morgan — CHANGES_REQUESTED** [review]
Thinking this won't build for any platform

File: bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/Guardian/Guardian.cs [hunk 12]
```diff
@@ -201,19 +224,27 @@ public ElectionPublicKey SharePublicKey()
 
     public void SaveGuardianKey(ElectionPublicKey key)
     {
-        _otherGuardianPublicKeys ??= new();
-        _otherGuardianPublicKeys[key.OwnerId] = key;
+        if (!key.Key.IsInBounds())
+        {
+            throw new ArgumentOutOfRangeException(nameof(key));
+        }
```
[the remark this answers is not in the document]
Comment (AddressXception) [reply bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/Guardian/Guardian.cs:230]: it's a synthetic check to make sure there's a handle on the object. I added a new function to fill that responsibility sincei t wasn't clear. This is jsut input sanitization.

File: bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/Guardian/GuardianStorageExtensions.cs (hunk 4 above)
Comment (AddressXception) [reply bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/Guardian/GuardianStorageExtensions.cs:4]: I started with System.Text and struggled to get it to work correctly.

File: bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/KeyCeremonyMediator.cs (hunk 7 above)
Comment (AddressXception) [reply bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/KeyCeremonyMediator.cs:798]: we can switch it back for now if oyu want just say the word

File: bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/Guardian/Guardian.cs [hunk 13]
```diff
@@ -201,19 +224,27 @@ public ElectionPublicKey SharePublicKey()
...
     // generate_election_partial_key_backups
     public bool GenerateElectionPartialKeyBackups()
     {
-        _otherGuardianPublicKeys ??= new();
-
+        if (!AllGuardianKeysReceived)
+        {
+            throw new InvalidOperationException("Not all guardian keys have been received.");
+        }
         foreach (var guardianKey in _otherGuardianPublicKeys.Values)
```
[the remark this answers is not in the document]
Comment (AddressXception) [reply bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/Guardian/Guardian.cs:241]: i tried. There's an exponentiation in the math which isnt playing well with the async internals across the library boundary. will be a good candidate for optimization when that is in a better state.

File: bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/Guardian/Guardian.cs [hunk 14]
```diff
@@ -132,28 +152,35 @@ CeremonyDetails ceremonyDetails
...
-        Dictionary<string, ElectionPartialKeyBackup>? partialKeyBackup = null,
+        Dictionary<string, ElectionPartialKeyBackup>? backupsToShare = null,
         Dictionary<string, ElectionPartialKeyVerification>? guardianElectionPartialKeyVerifications = null
         )
     {
-        _electionKeys = keyPair;
+        _electionKeys = new(keyPair);
         GuardianId = keyPair.OwnerId;
         SequenceOrder = keyPair.SequenceOrder;
         CeremonyDetails = ceremonyDetails;
```
[the remark this answers is not in the document]
Comment (john-s-morgan) [reply bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/Guardian/Guardian.cs:175]: I have mixed feelings on this. With it sharing a reference with another object, we may end up with some unexpected mutations.

File: bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/KeyCeremonyMediator.cs (hunk 7 above)
Comment (john-s-morgan) [reply bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/KeyCeremonyMediator.cs:805]: def. I'll add an issue, because this is a good, but breaking change.

**Comment by john-s-morgan** [comment]
`make publish-ui` fails (1 error):

```msbuild
C:\repos\microsoft\electionguard-core2\src\electionguard-ui\ElectionGuard.UI\ViewModels\ViewKeyCeremonyViewModel.cs(84,29): error CS7036: There is no argument
 given that corresponds to the required parameter 'keyCeremonyService' of 'KeyCeremonyMediator.KeyCeremonyMediator(string, string, KeyCeremonyRecord, IKeyCere
monyService, IGuardianBackupService, IGuardianPublicKeyService, IVerificationService)' [C:\repos\microsoft\electionguard-core2\src\electionguard-ui\ElectionGu
ard.UI\ElectionGuard.UI.csproj::TargetFramework=net7.0-windows10.0.19041.0]
```

Looking into it

**Review by john-s-morgan — CHANGES_REQUESTED** [review]
Some small changes

**Comment by john-s-morgan** [comment]
`make test` fails on MSVC

File: src/electionguard-ui/ElectionGuard.UI.Lib/Models/ElectionPublicKey.cs
Comment (john-s-morgan) [inline src/electionguard-ui/ElectionGuard.UI.Lib/Models/ElectionPublicKey.cs:1]: This is where I was suggesting to add a validation to the Key property, on assignment.

File: bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/ElGamal.cs [hunk 15]
```diff
@@ -94,6 +105,27 @@ public static class HashedElgamal
...
+            if (publicKey == null || !publicKey.IsInBounds())
+            {
+                throw new ArgumentNullException(nameof(publicKey));
+            }
+            if (seed == null || !seed.IsInBounds())
+            {
+                throw new ArgumentNullException(nameof(seed));
+            }
+
+            Console.WriteLine($"HashedElGamalCiphertext Encrypting {length} bytes");
```
[the remark this answers is not in the document]
Comment (SteveMaier-IRT) [reply bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/ElGamal.cs:125]: Definately need to have a logger.  Not sure if we wrote an issue for this yet or not.

File: bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/KeyCeremonyMediator.cs (hunk 7 above)
Comment (john-s-morgan) [reply bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/KeyCeremonyMediator.cs:805]: #213

File: bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/Guardian/GuardianVerifyMethods.cs [hunk 16]
```diff
@@ -55,31 +54,32 @@ public void SaveElectionPartialKeyVerification(ElectionPartialKeyVerification ve
             return null;
         }
         return VerifyElectionPartialKeyBackup(
-            backup?.DesignatedId!, backup, publicKey, _electionKeys, keyCeremonyId);
+            backup?.DesignatedId!, backup!, publicKey, _myElectionKeys, keyCeremonyId);
```
[the remark this answers is not in the document]
Comment (AddressXception) [reply bindings/netstandard/ElectionGuard/ElectionGuard.ElectionSetup/Guardian/GuardianVerifyMethods.cs:57]: vs code still wants it

File: bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/BigMath.cs [hunk 17]
```diff
@@ -89,12 +92,20 @@ public static ElementModP PowModP(ElementModP b, ElementModQ e)
...
 
         public static ElementModP PowModP(ElementModQ b, ulong e)
         {
-            return PowModP(new ElementModP(b), new ElementModQ(e, true));
+            var bP = new ElementModP(b);
+            var eQ = new ElementModQ(e, true);
+            var ret = PowModP(bP, eQ);
+            eQ.Dispose();
+            bP.Dispose();
+            return ret;
```
[the remark this answers is not in the document]
Comment (AddressXception) [reply bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/BigMath.cs:108]: fixed where you called it out however this is a matter of sematic difference in code style preference and i think we should try to get the roslyn compiler to do the heavy lifting

File: bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/DisposableBase.cs [hunk 18]
```diff
@@ -6,7 +6,7 @@ namespace ElectionGuard
     /// </summary>
     public class DisposableBase : IDisposable
     {
-        private bool _disposedValue;
+        public bool IsDisposed { get; private set; }
```
[the remark this answers is not in the document]
Comment (AddressXception) [reply bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/DisposableBase.cs:9]: it could probably be internal now that i added `IsAddressable` however its useful to be able to check the state of these objects that wrap native code

**Review by SteveMaier-IRT — APPROVED** [review]
lgtm
