### PR TITLE
Fix/fix tally with spoiled

### LINKED ISSUE #460: 🐞 Running a tally with spoiled ballots Crashes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If ballots are moved from challenged to spoiled, the tally does not complete correctly.

The ballots also do not really moved to spoiled at all.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SteveMaier-IRT**
[//]: # (🚨 Please review the CONTRIBUTING.md in this repository. 💔Thank you!)

### Issue
Fixes #460 

### Description
Fixed the tally when there are spoiled ballots.
fixed the ability to change challenged ballots to spoiled.

### CODE REVIEW

File: bindings/netstandard/ElectionGuard/ElectionGuard.Decryption/Decryption/CiphertextDecryptionTally.cs [hunk 1]
```diff
@@ -114,9 +114,9 @@ public void AddBallot(CiphertextBallot ballot)
     // add a spoiled ballot which will not be decrypted
     public void AddSpoiledBallot(CiphertextBallot ballot)
     {
-        if (!_tally.HasBallot(ballot.ObjectId))
+        if (_tally.HasBallot(ballot.ObjectId))
```
Comment (SteveMaier-IRT) [inline bindings/netstandard/ElectionGuard/ElectionGuard.Decryption/Decryption/CiphertextDecryptionTally.cs:117]: Change the logic to invert.

File: bindings/netstandard/ElectionGuard/ElectionGuard.Decryption/Decryption/CiphertextDecryptionTally.cs [hunk 2]
```diff
@@ -144,9 +144,9 @@ public void AddSpoiledBallot(CiphertextBallot ballot)
         BallotShare ballotShare,
         CiphertextBallot ballot)
     {
-        if (!_tally.HasBallot(ballot.ObjectId))
+        if (_tally.HasBallot(ballot.ObjectId))
```
Comment (SteveMaier-IRT) [inline bindings/netstandard/ElectionGuard/ElectionGuard.Decryption/Decryption/CiphertextDecryptionTally.cs:147]: Changed logic to invert.

File: src/electionguard-ui/ElectionGuard.UI.Lib/Services/Database/BallotUploadService.cs [hunk 3]
```diff
@@ -35,4 +35,15 @@ public async Task<bool> DriveUsed(long serialNumber, string electionId)
...
+    public async Task DecrementBallotsChallenged(string uploadId)
+    {
+        var filter = FilterBuilder.And(FilterBuilder.Eq(Constants.UploadId, uploadId));
+        var upload = await GetByFieldAsync(Constants.UploadId, uploadId);
+        var update = Builders<BallotUpload>.Update
+                        .Set(Constants.BallotChallenged, upload!.BallotChallenged - 1)
+                        .Set(Constants.BallotSpoiled, upload!.BallotSpoiled + 1);
+
+        await UpdateAsync(filter, update);
+    }
```
Comment (SteveMaier-IRT) [inline src/electionguard-ui/ElectionGuard.UI.Lib/Services/Database/BallotUploadService.cs:48]: Method added to decrement the ballot challenged and increment the spoiled count.

File: src/electionguard-ui/ElectionGuard.UI.Lib/Services/Interfaces/IDatabaseService.cs [hunk 4]
```diff
@@ -61,6 +61,10 @@ internal static class Constants
 
     public readonly static string ObjectId = "ObjectId";
 
+    public readonly static string BallotChallenged = "BallotChallenged";
+
+    public readonly static string BallotSpoiled = "BallotSpoiled";
+
```
Comment (SteveMaier-IRT) [inline src/electionguard-ui/ElectionGuard.UI.Lib/Services/Interfaces/IDatabaseService.cs:67]: Add new fields to use.

File: src/electionguard-ui/ElectionGuard.UI/ElectionGuard.UI.csproj [hunk 5]
```diff
@@ -19,7 +19,7 @@
 
 		<!-- Versions -->
 		<ApplicationDisplayVersion>1.91</ApplicationDisplayVersion>
-		<ApplicationVersion>13</ApplicationVersion>
+		<ApplicationVersion>14</ApplicationVersion>
```
Comment (SteveMaier-IRT) [inline src/electionguard-ui/ElectionGuard.UI/ElectionGuard.UI.csproj:22]: Upgrade to version 14

File: src/electionguard-ui/ElectionGuard.UI/Models/TallyCeremonyChecklist.cs [hunk 6]
```diff
@@ -5,21 +5,26 @@ public partial class TallyCeremonyChecklist : ObservableObject
     [ObservableProperty]
     private bool _quorumReached;
 
-    public bool TallyStarted => State >= TallyState.TallyStarted;
-    public bool SubtaliesCombined => State >= TallyState.PendingGuardianDecryptShares;
-    public bool AllDecryptionSharesComputed => SubtaliesCombined && (
-        State > TallyState.PendingGuardianDecryptShares ||
-        (State == TallyState.PendingGuardianDecryptShares && _sharesComputed >= _quorum));
+    [ObservableProperty]
```
Comment (SteveMaier-IRT) [inline src/electionguard-ui/ElectionGuard.UI/Models/TallyCeremonyChecklist.cs:8]: Converted all of these fields to observable properties to be seen better by the bindings

File: src/electionguard-ui/ElectionGuard.UI/Resx/AppResources.resx [hunk 7]
```diff
@@ -532,7 +532,7 @@
     <value>View Tally</value>
   </data>
   <data name="ChallengedText" xml:space="preserve">
-    <value>Challenged</value>
+    <value>Challenge</value>
```
Comment (SteveMaier-IRT) [inline src/electionguard-ui/ElectionGuard.UI/Resx/AppResources.resx:535]: Removed the d so that it does not wrap

File: src/electionguard-ui/ElectionGuard.UI/ViewModels/BallotUploadViewModel.cs [hunk 8]
```diff
@@ -58,8 +58,8 @@ public partial class BallotUploadViewModel : BaseViewModel
         {
             var record = await _manifestService.GetByElectionIdAsync(value);
             using var manifest = new Manifest(record?.ManifestData);
-            _manifestHash = new(manifest.CryptoHash());
             _internalManifest = new InternalManifest(manifest);
+            _manifestHash = new(_internalManifest.ManifestHash);
```
Comment (SteveMaier-IRT) [inline src/electionguard-ui/ElectionGuard.UI/ViewModels/BallotUploadViewModel.cs:62]: Changed to get the hash from the internal manifest instead of from the manifest.

File: src/electionguard-ui/ElectionGuard.UI/ViewModels/ChallengedPopupViewModel.cs [hunk 9]
```diff
@@ -20,20 +22,30 @@ public partial class ChallengedPopupViewModel : BaseViewModel
...
     partial void OnElectionIdChanged(string value)
     {
         if (!string.IsNullOrEmpty(value))
         {
-            _ = Shell.Current.CurrentPage.Dispatcher.DispatchAsync(async () => await SetElection(value));
+            _ = Shell.Current.CurrentPage.Dispatcher.DispatchAsync(async () =>
+            {
+                SearchText = string.Empty;
+                await SetElection(value);
+            });
```
Comment (SteveMaier-IRT) [inline src/electionguard-ui/ElectionGuard.UI/ViewModels/ChallengedPopupViewModel.cs:48]: Clear the search text if the election id changed

File: src/electionguard-ui/ElectionGuard.UI/ViewModels/ChallengedPopupViewModel.cs [hunk 10]
```diff
@@ -54,9 +66,32 @@ private async Task SpoilBallot()
         var answer = await Shell.Current.CurrentPage.DisplayAlert(AppResources.SpoilBallotText, AppResources.SpoilConfirmationText, AppResources.YesText, AppResources.NoText);
         if (answer)
         {
+            // update the ballot data to spoiled
```
Comment (SteveMaier-IRT) [inline src/electionguard-ui/ElectionGuard.UI/ViewModels/ChallengedPopupViewModel.cs:69]: Completed the converting of the challenged ballot to a spoiled and changing the tally and other structures

**Review by AddressXception — APPROVED** [review]

File: src/electionguard-ui/ElectionGuard.UI/ViewModels/ElectionViewModel.cs [hunk 11]
```diff
@@ -142,36 +142,41 @@ public partial class ElectionViewModel : BaseViewModel
...
+            BallotUploads.Add(upload);
+            BallotCountTotal += upload.BallotCount;
+            BallotAddedTotal += upload.BallotImported;
+            BallotChallengedTotal += upload.BallotChallenged;
+            BallotSpoiledTotal += upload.BallotSpoiled;
+            BallotDuplicateTotal += upload.BallotDuplicated;
+            BallotRejectedTotal += upload.BallotRejected;
+        });
+    }
+
```
Comment (SteveMaier-IRT) [inline src/electionguard-ui/ElectionGuard.UI/ViewModels/ElectionViewModel.cs:166]: Cleanup the refresh to a separate method that can be called when the challenge spoiled ballot is changed.

File: src/electionguard/ballot.cpp [hunk 12]
```diff
@@ -1166,10 +1166,6 @@ namespace electionguard
             Log::error(":ballot has already been cast");
             throw invalid_argument("ballot has already been cast");
         }
-        if (pimpl->state == BallotBoxState::challenged) {
-            Log::error(":ballot has already been challenged");
-            throw invalid_argument("ballot has already been challenged");
-        }
```
Comment (SteveMaier-IRT) [inline src/electionguard/ballot.cpp:1172]: Removed this so that a challeged ballot can be converted to a spoiled ballot.
