### PR TITLE
Finish Range proof coding

### LINKED ISSUE #389: 🐞 Contest proof needs to use Chaum Pedersen Ranged Proofs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently a contest is using a disjunctive proof, not a ranged proof. The serialization is expecting a ranged proof. These need to align.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SteveMaier-IRT**
[//]: # (🚨 Please review the CONTRIBUTING.md in this repository. 💔Thank you!)
Fixes #389, #420 

### Description
Changed proofs to use the ranged proof instead of disjunctive proof.
Fixed test data for WASM build

### Testing
Run an election or all of the tests.

### CODE REVIEW

File: bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/EncryptionMediator.cs [hunk 1]
```diff
@@ -41,7 +41,7 @@ public class EncryptionMediator : DisposableBase
             PlaintextBallot plaintext, bool verifyProofs = false)
         {
             // TODO: default to usePrecomputedValues: false
```
Comment (AddressXception) [inline bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/EncryptionMediator.cs:43]: should we remove the todo here since you made the change? i think this was an artifact left over from november

File: bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/GeneratedInterop/CiphertextBallotSelection.generated.cs [hunk 2]
```diff
@@ -287,7 +288,8 @@ CiphertextBallotSelectionHandle handle
                 SetLastError = true)]
             internal static extern Status GetProof(
                 CiphertextBallotSelectionHandle handle,
-                out NativeInterface.DisjunctiveChaumPedersenProof.DisjunctiveChaumPedersenProofHandle objectId
+                out NativeInterface.RangedChaumPedersenProof.RangedChaumPedersenProofHandle objectId
+                // out NativeInterface.DisjunctiveChaumPedersenProof.DisjunctiveChaumPedersenProofHandle objectId
```
Comment (AddressXception) [inline bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/GeneratedInterop/CiphertextBallotSelection.generated.cs:292]: what do you want to do about the commented lines throughout?

**Review by AddressXception — CHANGES_REQUESTED** [review]

File: bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/GeneratedInterop/CiphertextBallotSelection.generated.cs (hunk 2 above)
Comment (SteveMaier-IRT) [reply bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/GeneratedInterop/CiphertextBallotSelection.generated.cs:292]: Removing them.  thx

File: bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/EncryptionMediator.cs (hunk 1 above)
Comment (SteveMaier-IRT) [reply bindings/netstandard/ElectionGuard/ElectionGuard.Encryption/EncryptionMediator.cs:43]: Removed

**Review by AddressXception — APPROVED** [review]
